server:
  port: 1999
  servlet:
    context-path: /api

spring:
  main:
    banner-mode: off
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: plantilla
    password: plantilla
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: jvaleriom@vallegrande.edu.pe
    password: pqbhgbjuuslmtsdh
    port: 587
    properties:
      mail:
        ssl:
          enable: true
        smtp:
          auth: true
          starttls:
            enable: true       
            required: true     
    protocol: smtp
    test-connection: false

logging:
  level:
    root: INFO
    com.memorynotfound: DEBUG
    org.springframework.web: INFO
    # org.springframework.security: INFO
    org.hibernate.SQL: debug


  